CREATE TABLE IF NOT EXISTS contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    fullname TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    wilaya TEXT,
    daira TEXT,
    client_type TEXT,
    searching_for TEXT,
    preferred_location_type TEXT,
    house_finishing TEXT,
    renting_floor_looking_for TEXT,
    is_married BOOLEAN DEFAULT 0,
    min_budget INTEGER,
    max_budget INTEGER,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME,
    FOREIGN KEY(user_id) REFERENCES users(id)
);
