CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    to_id INTEGER NOT NULL REFERENCES users(id),
    root_id INTEGER NOT NULL REFERENCES users(id),
    title VARCHAR(250) NOT NULL,
    content TEXT(1250) NOT NULL,
    is_completed BOOLEAN DEFAULT 0,
    due_date DATE DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME
);