// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: building.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const countUserBuildings = `-- name: CountUserBuildings :one
SELECT count(id) FROM buildings WHERE user_id = ? and deleted_at IS NULL
`

func (q *Queries) CountUserBuildings(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserBuildings, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserBuildingsByStatus = `-- name: CountUserBuildingsByStatus :one
SELECT count(id) FROM buildings WHERE user_id = ? and status = ? and deleted_at IS NULL
`

type CountUserBuildingsByStatusParams struct {
	UserID int64          `json:"user_id"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) CountUserBuildingsByStatus(ctx context.Context, arg CountUserBuildingsByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserBuildingsByStatus, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBuilding = `-- name: CreateBuilding :execresult
INSERT INTO buildings (
  user_id, location, title, wilaya, daira, building_type, is_promotion_building, is_residency,
  status, price, surface_total, surface_built, rooms, bathrooms, floors_total, parking_spaces,
  is_by_the_sea, has_water, has_electricity, has_gas, has_internet, has_garden, has_pool,
  has_elevator, has_central_heating, has_water_tank, has_air_conditioner, has_equipped_kitchen,
  has_terrace, has_notarial_deed, has_land_booklet, has_act_in_joint_ownership,
  has_certificate_of_conformity, has_decision, has_concession, has_stamped_paper,
  has_building_permit, has_off_plan_sales_contract, building_finished_type,
  acceptable_payment_type, furnished, year_built, description, shareable_link
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateBuildingParams struct {
	UserID                     int64           `json:"user_id"`
	Location                   sql.NullString  `json:"location"`
	Title                      sql.NullString  `json:"title"`
	Wilaya                     sql.NullString  `json:"wilaya"`
	Daira                      sql.NullString  `json:"daira"`
	BuildingType               sql.NullString  `json:"building_type"`
	IsPromotionBuilding        sql.NullBool    `json:"is_promotion_building"`
	IsResidency                sql.NullBool    `json:"is_residency"`
	Status                     sql.NullString  `json:"status"`
	Price                      sql.NullInt64   `json:"price"`
	SurfaceTotal               sql.NullFloat64 `json:"surface_total"`
	SurfaceBuilt               sql.NullFloat64 `json:"surface_built"`
	Rooms                      sql.NullInt64   `json:"rooms"`
	Bathrooms                  sql.NullInt64   `json:"bathrooms"`
	FloorsTotal                sql.NullInt64   `json:"floors_total"`
	ParkingSpaces              sql.NullInt64   `json:"parking_spaces"`
	IsByTheSea                 sql.NullBool    `json:"is_by_the_sea"`
	HasWater                   sql.NullBool    `json:"has_water"`
	HasElectricity             sql.NullBool    `json:"has_electricity"`
	HasGas                     sql.NullBool    `json:"has_gas"`
	HasInternet                sql.NullBool    `json:"has_internet"`
	HasGarden                  sql.NullBool    `json:"has_garden"`
	HasPool                    sql.NullBool    `json:"has_pool"`
	HasElevator                sql.NullBool    `json:"has_elevator"`
	HasCentralHeating          sql.NullBool    `json:"has_central_heating"`
	HasWaterTank               sql.NullBool    `json:"has_water_tank"`
	HasAirConditioner          sql.NullBool    `json:"has_air_conditioner"`
	HasEquippedKitchen         sql.NullBool    `json:"has_equipped_kitchen"`
	HasTerrace                 sql.NullBool    `json:"has_terrace"`
	HasNotarialDeed            sql.NullBool    `json:"has_notarial_deed"`
	HasLandBooklet             sql.NullBool    `json:"has_land_booklet"`
	HasActInJointOwnership     sql.NullBool    `json:"has_act_in_joint_ownership"`
	HasCertificateOfConformity sql.NullBool    `json:"has_certificate_of_conformity"`
	HasDecision                sql.NullBool    `json:"has_decision"`
	HasConcession              sql.NullBool    `json:"has_concession"`
	HasStampedPaper            sql.NullBool    `json:"has_stamped_paper"`
	HasBuildingPermit          sql.NullBool    `json:"has_building_permit"`
	HasOffPlanSalesContract    sql.NullBool    `json:"has_off_plan_sales_contract"`
	BuildingFinishedType       sql.NullString  `json:"building_finished_type"`
	AcceptablePaymentType      sql.NullString  `json:"acceptable_payment_type"`
	Furnished                  sql.NullBool    `json:"furnished"`
	YearBuilt                  sql.NullInt64   `json:"year_built"`
	Description                sql.NullString  `json:"description"`
	ShareableLink              sql.NullString  `json:"shareable_link"`
}

func (q *Queries) CreateBuilding(ctx context.Context, arg CreateBuildingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBuilding,
		arg.UserID,
		arg.Location,
		arg.Title,
		arg.Wilaya,
		arg.Daira,
		arg.BuildingType,
		arg.IsPromotionBuilding,
		arg.IsResidency,
		arg.Status,
		arg.Price,
		arg.SurfaceTotal,
		arg.SurfaceBuilt,
		arg.Rooms,
		arg.Bathrooms,
		arg.FloorsTotal,
		arg.ParkingSpaces,
		arg.IsByTheSea,
		arg.HasWater,
		arg.HasElectricity,
		arg.HasGas,
		arg.HasInternet,
		arg.HasGarden,
		arg.HasPool,
		arg.HasElevator,
		arg.HasCentralHeating,
		arg.HasWaterTank,
		arg.HasAirConditioner,
		arg.HasEquippedKitchen,
		arg.HasTerrace,
		arg.HasNotarialDeed,
		arg.HasLandBooklet,
		arg.HasActInJointOwnership,
		arg.HasCertificateOfConformity,
		arg.HasDecision,
		arg.HasConcession,
		arg.HasStampedPaper,
		arg.HasBuildingPermit,
		arg.HasOffPlanSalesContract,
		arg.BuildingFinishedType,
		arg.AcceptablePaymentType,
		arg.Furnished,
		arg.YearBuilt,
		arg.Description,
		arg.ShareableLink,
	)
}

const createBuildingDocument = `-- name: CreateBuildingDocument :exec
INSERT INTO building_documents (user_id, building_id, path, mimetype, size, thumbnail)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateBuildingDocumentParams struct {
	UserID     int64          `json:"user_id"`
	BuildingID int64          `json:"building_id"`
	Path       string         `json:"path"`
	Mimetype   sql.NullString `json:"mimetype"`
	Size       sql.NullInt64  `json:"size"`
	Thumbnail  sql.NullString `json:"thumbnail"`
}

func (q *Queries) CreateBuildingDocument(ctx context.Context, arg CreateBuildingDocumentParams) error {
	_, err := q.db.ExecContext(ctx, createBuildingDocument,
		arg.UserID,
		arg.BuildingID,
		arg.Path,
		arg.Mimetype,
		arg.Size,
		arg.Thumbnail,
	)
	return err
}

const createBuildingImage = `-- name: CreateBuildingImage :exec
INSERT INTO building_images (user_id, building_id, path, mimetype, size)
VALUES (?, ?, ?, ?, ?)
`

type CreateBuildingImageParams struct {
	UserID     int64          `json:"user_id"`
	BuildingID int64          `json:"building_id"`
	Path       string         `json:"path"`
	Mimetype   sql.NullString `json:"mimetype"`
	Size       sql.NullInt64  `json:"size"`
}

func (q *Queries) CreateBuildingImage(ctx context.Context, arg CreateBuildingImageParams) error {
	_, err := q.db.ExecContext(ctx, createBuildingImage,
		arg.UserID,
		arg.BuildingID,
		arg.Path,
		arg.Mimetype,
		arg.Size,
	)
	return err
}

const createBuildingVue = `-- name: CreateBuildingVue :exec
INSERT INTO building_vues(building_id, ip_address, user_agent)
VALUES(?, ?, ?)
`

type CreateBuildingVueParams struct {
	BuildingID int64  `json:"building_id"`
	IpAddress  string `json:"ip_address"`
	UserAgent  string `json:"user_agent"`
}

func (q *Queries) CreateBuildingVue(ctx context.Context, arg CreateBuildingVueParams) error {
	_, err := q.db.ExecContext(ctx, createBuildingVue, arg.BuildingID, arg.IpAddress, arg.UserAgent)
	return err
}

const deleteBuilding = `-- name: DeleteBuilding :exec
UPDATE buildings SET deleted_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND id = ? AND deleted_at is NULL
`

type DeleteBuildingParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) DeleteBuilding(ctx context.Context, arg DeleteBuildingParams) error {
	_, err := q.db.ExecContext(ctx, deleteBuilding, arg.UserID, arg.ID)
	return err
}

const deleteBuildingDocument = `-- name: DeleteBuildingDocument :exec
UPDATE building_documents SET deleted_at = CURRENT_TIMESTAMP
WHERE building_id = ? AND user_id = ? AND id = ? AND deleted_at is NULL
`

type DeleteBuildingDocumentParams struct {
	BuildingID int64 `json:"building_id"`
	UserID     int64 `json:"user_id"`
	ID         int64 `json:"id"`
}

func (q *Queries) DeleteBuildingDocument(ctx context.Context, arg DeleteBuildingDocumentParams) error {
	_, err := q.db.ExecContext(ctx, deleteBuildingDocument, arg.BuildingID, arg.UserID, arg.ID)
	return err
}

const deleteBuildingDocuments = `-- name: DeleteBuildingDocuments :exec
UPDATE building_documents SET deleted_at = CURRENT_TIMESTAMP
WHERE building_id = ? AND user_id = ? AND deleted_at is NULL
`

type DeleteBuildingDocumentsParams struct {
	BuildingID int64 `json:"building_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) DeleteBuildingDocuments(ctx context.Context, arg DeleteBuildingDocumentsParams) error {
	_, err := q.db.ExecContext(ctx, deleteBuildingDocuments, arg.BuildingID, arg.UserID)
	return err
}

const deleteBuildingImage = `-- name: DeleteBuildingImage :exec
UPDATE building_images SET deleted_at = CURRENT_TIMESTAMP
WHERE building_id = ? AND user_id = ? AND id = ? AND deleted_at is NULL
`

type DeleteBuildingImageParams struct {
	BuildingID int64 `json:"building_id"`
	UserID     int64 `json:"user_id"`
	ID         int64 `json:"id"`
}

func (q *Queries) DeleteBuildingImage(ctx context.Context, arg DeleteBuildingImageParams) error {
	_, err := q.db.ExecContext(ctx, deleteBuildingImage, arg.BuildingID, arg.UserID, arg.ID)
	return err
}

const deleteBuildingImages = `-- name: DeleteBuildingImages :exec
UPDATE building_images SET deleted_at = CURRENT_TIMESTAMP
WHERE building_id = ? AND user_id = ? AND deleted_at is NULL
`

type DeleteBuildingImagesParams struct {
	BuildingID int64 `json:"building_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) DeleteBuildingImages(ctx context.Context, arg DeleteBuildingImagesParams) error {
	_, err := q.db.ExecContext(ctx, deleteBuildingImages, arg.BuildingID, arg.UserID)
	return err
}

const getBuilding = `-- name: GetBuilding :one
SELECT id, user_id, location, title, wilaya, daira, building_type, is_promotion_building, is_residency, status, price, surface_total, surface_built, rooms, bathrooms, floors_total, parking_spaces, is_by_the_sea, has_water, has_electricity, has_gas, has_internet, has_garden, has_pool, has_elevator, has_central_heating, has_water_tank, has_air_conditioner, has_equipped_kitchen, has_terrace, has_notarial_deed, has_land_booklet, has_act_in_joint_ownership, has_certificate_of_conformity, has_decision, has_concession, has_stamped_paper, has_building_permit, has_off_plan_sales_contract, building_finished_type, acceptable_payment_type, furnished, year_built, description, shareable_link, created_at, updated_at, deleted_at FROM buildings
WHERE user_id = ? AND id = ? AND deleted_at is NULL
`

type GetBuildingParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) GetBuilding(ctx context.Context, arg GetBuildingParams) (Building, error) {
	row := q.db.QueryRowContext(ctx, getBuilding, arg.UserID, arg.ID)
	var i Building
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.Title,
		&i.Wilaya,
		&i.Daira,
		&i.BuildingType,
		&i.IsPromotionBuilding,
		&i.IsResidency,
		&i.Status,
		&i.Price,
		&i.SurfaceTotal,
		&i.SurfaceBuilt,
		&i.Rooms,
		&i.Bathrooms,
		&i.FloorsTotal,
		&i.ParkingSpaces,
		&i.IsByTheSea,
		&i.HasWater,
		&i.HasElectricity,
		&i.HasGas,
		&i.HasInternet,
		&i.HasGarden,
		&i.HasPool,
		&i.HasElevator,
		&i.HasCentralHeating,
		&i.HasWaterTank,
		&i.HasAirConditioner,
		&i.HasEquippedKitchen,
		&i.HasTerrace,
		&i.HasNotarialDeed,
		&i.HasLandBooklet,
		&i.HasActInJointOwnership,
		&i.HasCertificateOfConformity,
		&i.HasDecision,
		&i.HasConcession,
		&i.HasStampedPaper,
		&i.HasBuildingPermit,
		&i.HasOffPlanSalesContract,
		&i.BuildingFinishedType,
		&i.AcceptablePaymentType,
		&i.Furnished,
		&i.YearBuilt,
		&i.Description,
		&i.ShareableLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBuildingEmbeddings = `-- name: GetBuildingEmbeddings :one
SELECT id, building_id, embedding, created_at FROM building_embeddings where building_id = ?
`

func (q *Queries) GetBuildingEmbeddings(ctx context.Context, buildingID int64) (BuildingEmbedding, error) {
	row := q.db.QueryRowContext(ctx, getBuildingEmbeddings, buildingID)
	var i BuildingEmbedding
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const getBuildingsDairas = `-- name: GetBuildingsDairas :many
SELECT count(id), daira from buildings where user_id = ? group by daira
`

type GetBuildingsDairasRow struct {
	Count int64          `json:"count"`
	Daira sql.NullString `json:"daira"`
}

func (q *Queries) GetBuildingsDairas(ctx context.Context, userID int64) ([]GetBuildingsDairasRow, error) {
	rows, err := q.db.QueryContext(ctx, getBuildingsDairas, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBuildingsDairasRow{}
	for rows.Next() {
		var i GetBuildingsDairasRow
		if err := rows.Scan(&i.Count, &i.Daira); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBuildingsMap = `-- name: GetBuildingsMap :many
SELECT id, title, location from buildings where user_id = ?
`

type GetBuildingsMapRow struct {
	ID       int64          `json:"id"`
	Title    sql.NullString `json:"title"`
	Location sql.NullString `json:"location"`
}

func (q *Queries) GetBuildingsMap(ctx context.Context, userID int64) ([]GetBuildingsMapRow, error) {
	rows, err := q.db.QueryContext(ctx, getBuildingsMap, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBuildingsMapRow{}
	for rows.Next() {
		var i GetBuildingsMapRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Location); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBuildingsTotalChangeRate = `-- name: GetBuildingsTotalChangeRate :one
SELECT SUM(CASE WHEN strftime('%Y', created_at) = strftime('%Y', 'now') THEN price ELSE 0 END) AS current_year_total, SUM(CASE WHEN strftime('%Y', created_at) = strftime('%Y', 'now', '-1 year') THEN price ELSE 0 END) AS last_year_total, CASE WHEN SUM(CASE WHEN strftime('%Y', created_at) = strftime('%Y', 'now', '-1 year') THEN price ELSE 0 END) = 0 THEN NULL ELSE ROUND(((SUM(CASE WHEN strftime('%Y', created_at) = strftime('%Y', 'now') THEN price ELSE 0 END) - SUM(CASE WHEN strftime('%Y', created_at) = strftime('%Y', 'now', '-1 year') THEN price ELSE 0 END)) * 100.0 / SUM(CASE WHEN strftime('%Y', created_at) = strftime('%Y', 'now', '-1 year') THEN price ELSE 0 END)), 2) END AS percentage_change FROM buildings WHERE buildings.user_id = ?
`

type GetBuildingsTotalChangeRateRow struct {
	CurrentYearTotal sql.NullFloat64 `json:"current_year_total"`
	LastYearTotal    sql.NullFloat64 `json:"last_year_total"`
	PercentageChange interface{}     `json:"percentage_change"`
}

func (q *Queries) GetBuildingsTotalChangeRate(ctx context.Context, userID int64) (GetBuildingsTotalChangeRateRow, error) {
	row := q.db.QueryRowContext(ctx, getBuildingsTotalChangeRate, userID)
	var i GetBuildingsTotalChangeRateRow
	err := row.Scan(&i.CurrentYearTotal, &i.LastYearTotal, &i.PercentageChange)
	return i, err
}

const insertEmbeddings = `-- name: InsertEmbeddings :exec
INSERT INTO building_embeddings(building_id, embedding, created_at) VALUES (?, ?, CURRENT_TIMESTAMP)
`

type InsertEmbeddingsParams struct {
	BuildingID int64  `json:"building_id"`
	Embedding  string `json:"embedding"`
}

func (q *Queries) InsertEmbeddings(ctx context.Context, arg InsertEmbeddingsParams) error {
	_, err := q.db.ExecContext(ctx, insertEmbeddings, arg.BuildingID, arg.Embedding)
	return err
}

const listDocumentsForBuildingIDs = `-- name: ListDocumentsForBuildingIDs :many
SELECT id, user_id, building_id, path, mimetype, size, thumbnail, created_at, deleted_at FROM building_documents
WHERE building_id IN (/*SLICE:building_ids*/?) AND deleted_at is NULL
`

func (q *Queries) ListDocumentsForBuildingIDs(ctx context.Context, buildingIds []int64) ([]BuildingDocument, error) {
	query := listDocumentsForBuildingIDs
	var queryParams []interface{}
	if len(buildingIds) > 0 {
		for _, v := range buildingIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:building_ids*/?", strings.Repeat(",?", len(buildingIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:building_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildingDocument{}
	for rows.Next() {
		var i BuildingDocument
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BuildingID,
			&i.Path,
			&i.Mimetype,
			&i.Size,
			&i.Thumbnail,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesForBuildingIDs = `-- name: ListImagesForBuildingIDs :many
SELECT id, user_id, building_id, path, mimetype, size, created_at, deleted_at FROM building_images
WHERE building_id IN (/*SLICE:building_ids*/?) AND deleted_at is NULL
`

func (q *Queries) ListImagesForBuildingIDs(ctx context.Context, buildingIds []int64) ([]BuildingImage, error) {
	query := listImagesForBuildingIDs
	var queryParams []interface{}
	if len(buildingIds) > 0 {
		for _, v := range buildingIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:building_ids*/?", strings.Repeat(",?", len(buildingIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:building_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildingImage{}
	for rows.Next() {
		var i BuildingImage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BuildingID,
			&i.Path,
			&i.Mimetype,
			&i.Size,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaginatedBuildings = `-- name: ListPaginatedBuildings :many
SELECT id, user_id, location, title, wilaya, daira, building_type, is_promotion_building, is_residency, status, price, surface_total, surface_built, rooms, bathrooms, floors_total, parking_spaces, is_by_the_sea, has_water, has_electricity, has_gas, has_internet, has_garden, has_pool, has_elevator, has_central_heating, has_water_tank, has_air_conditioner, has_equipped_kitchen, has_terrace, has_notarial_deed, has_land_booklet, has_act_in_joint_ownership, has_certificate_of_conformity, has_decision, has_concession, has_stamped_paper, has_building_permit, has_off_plan_sales_contract, building_finished_type, acceptable_payment_type, furnished, year_built, description, shareable_link, created_at, updated_at, deleted_at FROM buildings
WHERE user_id = ? AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPaginatedBuildingsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPaginatedBuildings(ctx context.Context, arg ListPaginatedBuildingsParams) ([]Building, error) {
	rows, err := q.db.QueryContext(ctx, listPaginatedBuildings, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Building{}
	for rows.Next() {
		var i Building
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Location,
			&i.Title,
			&i.Wilaya,
			&i.Daira,
			&i.BuildingType,
			&i.IsPromotionBuilding,
			&i.IsResidency,
			&i.Status,
			&i.Price,
			&i.SurfaceTotal,
			&i.SurfaceBuilt,
			&i.Rooms,
			&i.Bathrooms,
			&i.FloorsTotal,
			&i.ParkingSpaces,
			&i.IsByTheSea,
			&i.HasWater,
			&i.HasElectricity,
			&i.HasGas,
			&i.HasInternet,
			&i.HasGarden,
			&i.HasPool,
			&i.HasElevator,
			&i.HasCentralHeating,
			&i.HasWaterTank,
			&i.HasAirConditioner,
			&i.HasEquippedKitchen,
			&i.HasTerrace,
			&i.HasNotarialDeed,
			&i.HasLandBooklet,
			&i.HasActInJointOwnership,
			&i.HasCertificateOfConformity,
			&i.HasDecision,
			&i.HasConcession,
			&i.HasStampedPaper,
			&i.HasBuildingPermit,
			&i.HasOffPlanSalesContract,
			&i.BuildingFinishedType,
			&i.AcceptablePaymentType,
			&i.Furnished,
			&i.YearBuilt,
			&i.Description,
			&i.ShareableLink,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuilding = `-- name: UpdateBuilding :exec
UPDATE buildings
SET
  title = ?,
  status = ?,
  location = ?,
  wilaya = ?,
  daira = ?,
  building_type = ?,
  is_promotion_building = ?,
  is_residency = ?,
  price = ?,
  surface_total = ?,
  surface_built = ?,
  rooms = ?,
  bathrooms = ?,
  floors_total = ?,
  parking_spaces = ?,
  is_by_the_sea = ?,
  has_water = ?,
  has_electricity = ?,
  has_gas = ?,
  has_internet = ?,
  has_garden = ?,
  has_pool = ?,
  has_elevator = ?,
  has_central_heating = ?,
  has_water_tank = ?,
  has_air_conditioner = ?,
  has_equipped_kitchen = ?,
  has_terrace = ?,
  has_notarial_deed = ?,
  has_land_booklet = ?,
  has_act_in_joint_ownership = ?,
  has_certificate_of_conformity = ?,
  has_decision = ?,
  has_concession = ?,
  has_stamped_paper = ?,
  has_building_permit = ?,
  has_off_plan_sales_contract = ?,
  building_finished_type = ?,
  acceptable_payment_type = ?,
  furnished = ?,
  year_built = ?,
  description = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND user_id = ? AND deleted_at is NULL
`

type UpdateBuildingParams struct {
	Title                      sql.NullString  `json:"title"`
	Status                     sql.NullString  `json:"status"`
	Location                   sql.NullString  `json:"location"`
	Wilaya                     sql.NullString  `json:"wilaya"`
	Daira                      sql.NullString  `json:"daira"`
	BuildingType               sql.NullString  `json:"building_type"`
	IsPromotionBuilding        sql.NullBool    `json:"is_promotion_building"`
	IsResidency                sql.NullBool    `json:"is_residency"`
	Price                      sql.NullInt64   `json:"price"`
	SurfaceTotal               sql.NullFloat64 `json:"surface_total"`
	SurfaceBuilt               sql.NullFloat64 `json:"surface_built"`
	Rooms                      sql.NullInt64   `json:"rooms"`
	Bathrooms                  sql.NullInt64   `json:"bathrooms"`
	FloorsTotal                sql.NullInt64   `json:"floors_total"`
	ParkingSpaces              sql.NullInt64   `json:"parking_spaces"`
	IsByTheSea                 sql.NullBool    `json:"is_by_the_sea"`
	HasWater                   sql.NullBool    `json:"has_water"`
	HasElectricity             sql.NullBool    `json:"has_electricity"`
	HasGas                     sql.NullBool    `json:"has_gas"`
	HasInternet                sql.NullBool    `json:"has_internet"`
	HasGarden                  sql.NullBool    `json:"has_garden"`
	HasPool                    sql.NullBool    `json:"has_pool"`
	HasElevator                sql.NullBool    `json:"has_elevator"`
	HasCentralHeating          sql.NullBool    `json:"has_central_heating"`
	HasWaterTank               sql.NullBool    `json:"has_water_tank"`
	HasAirConditioner          sql.NullBool    `json:"has_air_conditioner"`
	HasEquippedKitchen         sql.NullBool    `json:"has_equipped_kitchen"`
	HasTerrace                 sql.NullBool    `json:"has_terrace"`
	HasNotarialDeed            sql.NullBool    `json:"has_notarial_deed"`
	HasLandBooklet             sql.NullBool    `json:"has_land_booklet"`
	HasActInJointOwnership     sql.NullBool    `json:"has_act_in_joint_ownership"`
	HasCertificateOfConformity sql.NullBool    `json:"has_certificate_of_conformity"`
	HasDecision                sql.NullBool    `json:"has_decision"`
	HasConcession              sql.NullBool    `json:"has_concession"`
	HasStampedPaper            sql.NullBool    `json:"has_stamped_paper"`
	HasBuildingPermit          sql.NullBool    `json:"has_building_permit"`
	HasOffPlanSalesContract    sql.NullBool    `json:"has_off_plan_sales_contract"`
	BuildingFinishedType       sql.NullString  `json:"building_finished_type"`
	AcceptablePaymentType      sql.NullString  `json:"acceptable_payment_type"`
	Furnished                  sql.NullBool    `json:"furnished"`
	YearBuilt                  sql.NullInt64   `json:"year_built"`
	Description                sql.NullString  `json:"description"`
	ID                         int64           `json:"id"`
	UserID                     int64           `json:"user_id"`
}

func (q *Queries) UpdateBuilding(ctx context.Context, arg UpdateBuildingParams) error {
	_, err := q.db.ExecContext(ctx, updateBuilding,
		arg.Title,
		arg.Status,
		arg.Location,
		arg.Wilaya,
		arg.Daira,
		arg.BuildingType,
		arg.IsPromotionBuilding,
		arg.IsResidency,
		arg.Price,
		arg.SurfaceTotal,
		arg.SurfaceBuilt,
		arg.Rooms,
		arg.Bathrooms,
		arg.FloorsTotal,
		arg.ParkingSpaces,
		arg.IsByTheSea,
		arg.HasWater,
		arg.HasElectricity,
		arg.HasGas,
		arg.HasInternet,
		arg.HasGarden,
		arg.HasPool,
		arg.HasElevator,
		arg.HasCentralHeating,
		arg.HasWaterTank,
		arg.HasAirConditioner,
		arg.HasEquippedKitchen,
		arg.HasTerrace,
		arg.HasNotarialDeed,
		arg.HasLandBooklet,
		arg.HasActInJointOwnership,
		arg.HasCertificateOfConformity,
		arg.HasDecision,
		arg.HasConcession,
		arg.HasStampedPaper,
		arg.HasBuildingPermit,
		arg.HasOffPlanSalesContract,
		arg.BuildingFinishedType,
		arg.AcceptablePaymentType,
		arg.Furnished,
		arg.YearBuilt,
		arg.Description,
		arg.ID,
		arg.UserID,
	)
	return err
}
