// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: contact.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const countContactsByEmail = `-- name: CountContactsByEmail :one
SELECT COUNT(*) FROM contacts WHERE email = ?
`

func (q *Queries) CountContactsByEmail(ctx context.Context, email sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContactsByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContactsByPhone = `-- name: CountContactsByPhone :one
SELECT COUNT(*) FROM contacts WHERE phone = ?
`

func (q *Queries) CountContactsByPhone(ctx context.Context, phone sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContactsByPhone, phone)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserContacts = `-- name: CountUserContacts :one
SELECT COUNT(*) FROM contacts WHERE user_id = ?
`

func (q *Queries) CountUserContacts(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserContacts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContact = `-- name: CreateContact :execresult
INSERT INTO contacts (
  user_id,
  fullname,
  phone,
  email,
  wilaya,
  daira,
  client_type,
  searching_for,
  preferred_location_type,
  house_finishing,
  renting_floor_looking_for,
  is_married,
  min_budget,
  max_budget,
  preferred_building_types,
  preferred_features,
  min_rooms,
  max_rooms,
  min_surface,
  max_surface,
  furnished,
  acceptable_payment_type,
  max_year_built,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
`

type CreateContactParams struct {
	UserID                 int64           `json:"user_id"`
	Fullname               string          `json:"fullname"`
	Phone                  sql.NullString  `json:"phone"`
	Email                  sql.NullString  `json:"email"`
	Wilaya                 sql.NullString  `json:"wilaya"`
	Daira                  sql.NullString  `json:"daira"`
	ClientType             sql.NullString  `json:"client_type"`
	SearchingFor           sql.NullString  `json:"searching_for"`
	PreferredLocationType  sql.NullString  `json:"preferred_location_type"`
	HouseFinishing         sql.NullString  `json:"house_finishing"`
	RentingFloorLookingFor sql.NullString  `json:"renting_floor_looking_for"`
	IsMarried              sql.NullBool    `json:"is_married"`
	MinBudget              sql.NullInt64   `json:"min_budget"`
	MaxBudget              sql.NullInt64   `json:"max_budget"`
	PreferredBuildingTypes sql.NullString  `json:"preferred_building_types"`
	PreferredFeatures      sql.NullString  `json:"preferred_features"`
	MinRooms               sql.NullInt64   `json:"min_rooms"`
	MaxRooms               sql.NullInt64   `json:"max_rooms"`
	MinSurface             sql.NullFloat64 `json:"min_surface"`
	MaxSurface             sql.NullFloat64 `json:"max_surface"`
	Furnished              sql.NullBool    `json:"furnished"`
	AcceptablePaymentType  sql.NullString  `json:"acceptable_payment_type"`
	MaxYearBuilt           sql.NullInt64   `json:"max_year_built"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createContact,
		arg.UserID,
		arg.Fullname,
		arg.Phone,
		arg.Email,
		arg.Wilaya,
		arg.Daira,
		arg.ClientType,
		arg.SearchingFor,
		arg.PreferredLocationType,
		arg.HouseFinishing,
		arg.RentingFloorLookingFor,
		arg.IsMarried,
		arg.MinBudget,
		arg.MaxBudget,
		arg.PreferredBuildingTypes,
		arg.PreferredFeatures,
		arg.MinRooms,
		arg.MaxRooms,
		arg.MinSurface,
		arg.MaxSurface,
		arg.Furnished,
		arg.AcceptablePaymentType,
		arg.MaxYearBuilt,
	)
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts
WHERE id = ? AND user_id = ?
`

type DeleteContactParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) error {
	_, err := q.db.ExecContext(ctx, deleteContact, arg.ID, arg.UserID)
	return err
}

const getAllContacts = `-- name: GetAllContacts :many
SELECT
  id,
  user_id,
  fullname,
  phone,
  email,
  wilaya,
  daira,
  client_type,
  searching_for,
  preferred_location_type,
  house_finishing,
  renting_floor_looking_for,
  is_married,
  min_budget,
  max_budget,
  created_at,
  updated_at
FROM contacts
WHERE user_id = ?
ORDER BY id DESC
`

type GetAllContactsRow struct {
	ID                     int64          `json:"id"`
	UserID                 int64          `json:"user_id"`
	Fullname               string         `json:"fullname"`
	Phone                  sql.NullString `json:"phone"`
	Email                  sql.NullString `json:"email"`
	Wilaya                 sql.NullString `json:"wilaya"`
	Daira                  sql.NullString `json:"daira"`
	ClientType             sql.NullString `json:"client_type"`
	SearchingFor           sql.NullString `json:"searching_for"`
	PreferredLocationType  sql.NullString `json:"preferred_location_type"`
	HouseFinishing         sql.NullString `json:"house_finishing"`
	RentingFloorLookingFor sql.NullString `json:"renting_floor_looking_for"`
	IsMarried              sql.NullBool   `json:"is_married"`
	MinBudget              sql.NullInt64  `json:"min_budget"`
	MaxBudget              sql.NullInt64  `json:"max_budget"`
	CreatedAt              sql.NullTime   `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
}

func (q *Queries) GetAllContacts(ctx context.Context, userID int64) ([]GetAllContactsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllContacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllContactsRow{}
	for rows.Next() {
		var i GetAllContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Fullname,
			&i.Phone,
			&i.Email,
			&i.Wilaya,
			&i.Daira,
			&i.ClientType,
			&i.SearchingFor,
			&i.PreferredLocationType,
			&i.HouseFinishing,
			&i.RentingFloorLookingFor,
			&i.IsMarried,
			&i.MinBudget,
			&i.MaxBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContact = `-- name: GetContact :one
SELECT
  id, user_id, fullname, phone, email, wilaya, daira, client_type, searching_for, preferred_location_type, house_finishing, renting_floor_looking_for, is_married, min_budget, max_budget, created_at, updated_at, deleted_at, preferred_building_types, preferred_features, min_rooms, max_rooms, min_surface, max_surface, furnished, acceptable_payment_type, max_year_built
FROM contacts
WHERE id = ? AND user_id = ?
`

type GetContactParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContact, arg.ID, arg.UserID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Fullname,
		&i.Phone,
		&i.Email,
		&i.Wilaya,
		&i.Daira,
		&i.ClientType,
		&i.SearchingFor,
		&i.PreferredLocationType,
		&i.HouseFinishing,
		&i.RentingFloorLookingFor,
		&i.IsMarried,
		&i.MinBudget,
		&i.MaxBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.PreferredBuildingTypes,
		&i.PreferredFeatures,
		&i.MinRooms,
		&i.MaxRooms,
		&i.MinSurface,
		&i.MaxSurface,
		&i.Furnished,
		&i.AcceptablePaymentType,
		&i.MaxYearBuilt,
	)
	return i, err
}

const getContactEmbeddings = `-- name: GetContactEmbeddings :one
SELECT id, contact_id, embedding, created_at FROM contact_embeddings where contact_id = ?
`

func (q *Queries) GetContactEmbeddings(ctx context.Context, contactID int64) (ContactEmbedding, error) {
	row := q.db.QueryRowContext(ctx, getContactEmbeddings, contactID)
	var i ContactEmbedding
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.Embedding,
		&i.CreatedAt,
	)
	return i, err
}

const getContactsById = `-- name: GetContactsById :many
SELECT
  id,
  user_id,
  phone
FROM contacts
WHERE user_id = ? AND id IN (/*SLICE:ids*/?)
ORDER BY id DESC
`

type GetContactsByIdParams struct {
	UserID int64   `json:"user_id"`
	Ids    []int64 `json:"ids"`
}

type GetContactsByIdRow struct {
	ID     int64          `json:"id"`
	UserID int64          `json:"user_id"`
	Phone  sql.NullString `json:"phone"`
}

func (q *Queries) GetContactsById(ctx context.Context, arg GetContactsByIdParams) ([]GetContactsByIdRow, error) {
	query := getContactsById
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContactsByIdRow{}
	for rows.Next() {
		var i GetContactsByIdRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Phone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactsList = `-- name: GetContactsList :many
SELECT
  id, user_id, fullname, phone, email, wilaya, daira, client_type, searching_for, preferred_location_type, house_finishing, renting_floor_looking_for, is_married, min_budget, max_budget, created_at, updated_at, deleted_at, preferred_building_types, preferred_features, min_rooms, max_rooms, min_surface, max_surface, furnished, acceptable_payment_type, max_year_built
FROM contacts
WHERE id IN (/*SLICE:contact_ids*/?) AND user_id = ?
`

type GetContactsListParams struct {
	ContactIds []int64 `json:"contact_ids"`
	UserID     int64   `json:"user_id"`
}

func (q *Queries) GetContactsList(ctx context.Context, arg GetContactsListParams) ([]Contact, error) {
	query := getContactsList
	var queryParams []interface{}
	if len(arg.ContactIds) > 0 {
		for _, v := range arg.ContactIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:contact_ids*/?", strings.Repeat(",?", len(arg.ContactIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:contact_ids*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.UserID)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Fullname,
			&i.Phone,
			&i.Email,
			&i.Wilaya,
			&i.Daira,
			&i.ClientType,
			&i.SearchingFor,
			&i.PreferredLocationType,
			&i.HouseFinishing,
			&i.RentingFloorLookingFor,
			&i.IsMarried,
			&i.MinBudget,
			&i.MaxBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PreferredBuildingTypes,
			&i.PreferredFeatures,
			&i.MinRooms,
			&i.MaxRooms,
			&i.MinSurface,
			&i.MaxSurface,
			&i.Furnished,
			&i.AcceptablePaymentType,
			&i.MaxYearBuilt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContactsWithEmbeddings = `-- name: GetContactsWithEmbeddings :many
SELECT
  contacts.id,
  contact_embeddings.embedding
FROM contacts
RIGHT JOIN contact_embeddings ON contact_embeddings.contact_id = contacts.id
WHERE user_id = ?
ORDER BY contacts.id DESC
`

type GetContactsWithEmbeddingsRow struct {
	ID        sql.NullInt64 `json:"id"`
	Embedding string        `json:"embedding"`
}

func (q *Queries) GetContactsWithEmbeddings(ctx context.Context, userID int64) ([]GetContactsWithEmbeddingsRow, error) {
	rows, err := q.db.QueryContext(ctx, getContactsWithEmbeddings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetContactsWithEmbeddingsRow{}
	for rows.Next() {
		var i GetContactsWithEmbeddingsRow
		if err := rows.Scan(&i.ID, &i.Embedding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertContactEmbeddings = `-- name: InsertContactEmbeddings :exec
INSERT INTO contact_embeddings(contact_id, embedding, created_at) VALUES (?, ?, CURRENT_TIMESTAMP)
`

type InsertContactEmbeddingsParams struct {
	ContactID int64  `json:"contact_id"`
	Embedding string `json:"embedding"`
}

func (q *Queries) InsertContactEmbeddings(ctx context.Context, arg InsertContactEmbeddingsParams) error {
	_, err := q.db.ExecContext(ctx, insertContactEmbeddings, arg.ContactID, arg.Embedding)
	return err
}
