// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Building struct {
	ID                         int64           `json:"id"`
	UserID                     int64           `json:"user_id"`
	Location                   sql.NullString  `json:"location"`
	Title                      sql.NullString  `json:"title"`
	Wilaya                     sql.NullString  `json:"wilaya"`
	Daira                      sql.NullString  `json:"daira"`
	BuildingType               sql.NullString  `json:"building_type"`
	IsPromotionBuilding        sql.NullBool    `json:"is_promotion_building"`
	IsResidency                sql.NullBool    `json:"is_residency"`
	Status                     sql.NullString  `json:"status"`
	Price                      sql.NullInt64   `json:"price"`
	SurfaceTotal               sql.NullFloat64 `json:"surface_total"`
	SurfaceBuilt               sql.NullFloat64 `json:"surface_built"`
	Rooms                      sql.NullInt64   `json:"rooms"`
	Bathrooms                  sql.NullInt64   `json:"bathrooms"`
	FloorsTotal                sql.NullInt64   `json:"floors_total"`
	ParkingSpaces              sql.NullInt64   `json:"parking_spaces"`
	IsByTheSea                 sql.NullBool    `json:"is_by_the_sea"`
	HasWater                   sql.NullBool    `json:"has_water"`
	HasElectricity             sql.NullBool    `json:"has_electricity"`
	HasGas                     sql.NullBool    `json:"has_gas"`
	HasInternet                sql.NullBool    `json:"has_internet"`
	HasGarden                  sql.NullBool    `json:"has_garden"`
	HasPool                    sql.NullBool    `json:"has_pool"`
	HasElevator                sql.NullBool    `json:"has_elevator"`
	HasCentralHeating          sql.NullBool    `json:"has_central_heating"`
	HasWaterTank               sql.NullBool    `json:"has_water_tank"`
	HasAirConditioner          sql.NullBool    `json:"has_air_conditioner"`
	HasEquippedKitchen         sql.NullBool    `json:"has_equipped_kitchen"`
	HasTerrace                 sql.NullBool    `json:"has_terrace"`
	HasNotarialDeed            sql.NullBool    `json:"has_notarial_deed"`
	HasLandBooklet             sql.NullBool    `json:"has_land_booklet"`
	HasActInJointOwnership     sql.NullBool    `json:"has_act_in_joint_ownership"`
	HasCertificateOfConformity sql.NullBool    `json:"has_certificate_of_conformity"`
	HasDecision                sql.NullBool    `json:"has_decision"`
	HasConcession              sql.NullBool    `json:"has_concession"`
	HasStampedPaper            sql.NullBool    `json:"has_stamped_paper"`
	HasBuildingPermit          sql.NullBool    `json:"has_building_permit"`
	HasOffPlanSalesContract    sql.NullBool    `json:"has_off_plan_sales_contract"`
	BuildingFinishedType       sql.NullString  `json:"building_finished_type"`
	AcceptablePaymentType      sql.NullString  `json:"acceptable_payment_type"`
	Furnished                  sql.NullBool    `json:"furnished"`
	YearBuilt                  sql.NullInt64   `json:"year_built"`
	Description                sql.NullString  `json:"description"`
	ShareableLink              sql.NullString  `json:"shareable_link"`
	CreatedAt                  sql.NullTime    `json:"created_at"`
	UpdatedAt                  sql.NullTime    `json:"updated_at"`
	DeletedAt                  sql.NullTime    `json:"deleted_at"`
}

type BuildingDocument struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	BuildingID int64          `json:"building_id"`
	Path       string         `json:"path"`
	Mimetype   sql.NullString `json:"mimetype"`
	Size       sql.NullInt64  `json:"size"`
	Thumbnail  sql.NullString `json:"thumbnail"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
}

type BuildingEmbedding struct {
	ID         int64        `json:"id"`
	BuildingID int64        `json:"building_id"`
	Embedding  string       `json:"embedding"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type BuildingImage struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	BuildingID int64          `json:"building_id"`
	Path       string         `json:"path"`
	Mimetype   sql.NullString `json:"mimetype"`
	Size       sql.NullInt64  `json:"size"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
}

type BuildingVue struct {
	ID         int64        `json:"id"`
	BuildingID int64        `json:"building_id"`
	ViewedAt   sql.NullTime `json:"viewed_at"`
	IpAddress  string       `json:"ip_address"`
	UserAgent  string       `json:"user_agent"`
}

type CalendarEvent struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	ForDate   time.Time    `json:"for_date"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Contact struct {
	ID                     int64           `json:"id"`
	UserID                 int64           `json:"user_id"`
	Fullname               string          `json:"fullname"`
	Phone                  sql.NullString  `json:"phone"`
	Email                  sql.NullString  `json:"email"`
	Wilaya                 sql.NullString  `json:"wilaya"`
	Daira                  sql.NullString  `json:"daira"`
	ClientType             sql.NullString  `json:"client_type"`
	SearchingFor           sql.NullString  `json:"searching_for"`
	PreferredLocationType  sql.NullString  `json:"preferred_location_type"`
	HouseFinishing         sql.NullString  `json:"house_finishing"`
	RentingFloorLookingFor sql.NullString  `json:"renting_floor_looking_for"`
	IsMarried              sql.NullBool    `json:"is_married"`
	MinBudget              sql.NullInt64   `json:"min_budget"`
	MaxBudget              sql.NullInt64   `json:"max_budget"`
	CreatedAt              sql.NullTime    `json:"created_at"`
	UpdatedAt              sql.NullTime    `json:"updated_at"`
	DeletedAt              sql.NullTime    `json:"deleted_at"`
	PreferredBuildingTypes sql.NullString  `json:"preferred_building_types"`
	PreferredFeatures      sql.NullString  `json:"preferred_features"`
	MinRooms               sql.NullInt64   `json:"min_rooms"`
	MaxRooms               sql.NullInt64   `json:"max_rooms"`
	MinSurface             sql.NullFloat64 `json:"min_surface"`
	MaxSurface             sql.NullFloat64 `json:"max_surface"`
	Furnished              sql.NullBool    `json:"furnished"`
	AcceptablePaymentType  sql.NullString  `json:"acceptable_payment_type"`
	MaxYearBuilt           sql.NullInt64   `json:"max_year_built"`
}

type ContactEmbedding struct {
	ID        int64        `json:"id"`
	ContactID int64        `json:"contact_id"`
	Embedding string       `json:"embedding"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Report struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type SmsQueue struct {
	ID              int64          `json:"id"`
	UserID          int64          `json:"user_id"`
	Title           string         `json:"title"`
	Content         string         `json:"content"`
	FromNumber      string         `json:"from_number"`
	Status          sql.NullString `json:"status"`
	TotalRecipients int64          `json:"total_recipients"`
	SentCount       sql.NullInt64  `json:"sent_count"`
	FailedCount     sql.NullInt64  `json:"failed_count"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	ScheduledAt     sql.NullTime   `json:"scheduled_at"`
	SentAt          sql.NullTime   `json:"sent_at"`
}

type SmsQueueContact struct {
	ID          int64          `json:"id"`
	SmsQueueID  int64          `json:"sms_queue_id"`
	PhoneNumber string         `json:"phone_number"`
	Status      sql.NullString `json:"status"`
	Error       sql.NullString `json:"error"`
	SentAt      sql.NullTime   `json:"sent_at"`
}

type Task struct {
	ID          int64        `json:"id"`
	ToID        int64        `json:"to_id"`
	RootID      int64        `json:"root_id"`
	Title       string       `json:"title"`
	Content     interface{}  `json:"content"`
	IsCompleted sql.NullBool `json:"is_completed"`
	DueDate     sql.NullTime `json:"due_date"`
	CreatedAt   sql.NullTime `json:"created_at"`
	UpdatedAt   sql.NullTime `json:"updated_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID            int64          `json:"id"`
	Fullname      string         `json:"fullname"`
	Role          int64          `json:"role"`
	RootID        interface{}    `json:"root_id"`
	Email         string         `json:"email"`
	Phone         string         `json:"phone"`
	AgencyName    string         `json:"agency_name"`
	AgencyAddress string         `json:"agency_address"`
	AgencyLogo    sql.NullString `json:"agency_logo"`
	Wilaya        string         `json:"wilaya"`
	Daira         string         `json:"daira"`
	Password      string         `json:"password"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	DeletedAt     sql.NullTime   `json:"deleted_at"`
}
