// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment.sql

package db

import (
	"context"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (
    user_id, payload
) VALUES (
    ?, ?
)
`

type CreatePaymentParams struct {
	UserID  int64  `json:"user_id"`
	Payload string `json:"payload"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, createPayment, arg.UserID, arg.Payload)
	return err
}
