// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: report.sql

package db

import (
	"context"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
    user_id, title, content
) VALUES (
    ?, ?, ?
)
RETURNING id, user_id, title, content, created_at, updated_at, deleted_at
`

type CreateReportParams struct {
	UserID  int64  `json:"user_id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, createReport, arg.UserID, arg.Title, arg.Content)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
UPDATE reports set deleted_at = CURRENT_TIMESTAMP where id = ? and user_id = ?
`

type DeleteReportParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteReport(ctx context.Context, arg DeleteReportParams) error {
	_, err := q.db.ExecContext(ctx, deleteReport, arg.ID, arg.UserID)
	return err
}

const getUserReportById = `-- name: GetUserReportById :one
SELECT id, user_id, title, content, created_at, updated_at, deleted_at from reports where user_id = ? and id = ?
`

type GetUserReportByIdParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) GetUserReportById(ctx context.Context, arg GetUserReportByIdParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, getUserReportById, arg.UserID, arg.ID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserReports = `-- name: GetUserReports :many
SELECT id, user_id, title, content, created_at, updated_at, deleted_at from reports where user_id = ? and deleted_at is null ORDER BY id desc
`

func (q *Queries) GetUserReports(ctx context.Context, userID int64) ([]Report, error) {
	rows, err := q.db.QueryContext(ctx, getUserReports, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReport = `-- name: UpdateReport :exec
UPDATE reports SET
title = ?,
content = ?,
updated_at = CURRENT_TIMESTAMP
WHERE id = ? and user_id = ?
`

type UpdateReportParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	ID      int64  `json:"id"`
	UserID  int64  `json:"user_id"`
}

func (q *Queries) UpdateReport(ctx context.Context, arg UpdateReportParams) error {
	_, err := q.db.ExecContext(ctx, updateReport,
		arg.Title,
		arg.Content,
		arg.ID,
		arg.UserID,
	)
	return err
}
