// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shareable.sql

package db

import (
	"context"
	"database/sql"
)

const createShareable = `-- name: CreateShareable :one
INSERT INTO shareables (token, model_type, model_id, user_id)
VALUES (?, ?, ?, ?)
RETURNING id, token, user_id, model_type, model_id, created_at
`

type CreateShareableParams struct {
	Token     string `json:"token"`
	ModelType string `json:"model_type"`
	ModelID   int64  `json:"model_id"`
	UserID    int64  `json:"user_id"`
}

func (q *Queries) CreateShareable(ctx context.Context, arg CreateShareableParams) (Shareable, error) {
	row := q.db.QueryRowContext(ctx, createShareable,
		arg.Token,
		arg.ModelType,
		arg.ModelID,
		arg.UserID,
	)
	var i Shareable
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ModelType,
		&i.ModelID,
		&i.CreatedAt,
	)
	return i, err
}

const getShareable = `-- name: GetShareable :one
SELECT id, token, user_id, model_type, model_id, created_at FROM shareables 
WHERE token = ?
`

func (q *Queries) GetShareable(ctx context.Context, token string) (Shareable, error) {
	row := q.db.QueryRowContext(ctx, getShareable, token)
	var i Shareable
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ModelType,
		&i.ModelID,
		&i.CreatedAt,
	)
	return i, err
}

const getShareableByModelId = `-- name: GetShareableByModelId :one
SELECT id, token, user_id, model_type, model_id, created_at from shareables where model_type = ? and model_id = ? LIMIT 1
`

type GetShareableByModelIdParams struct {
	ModelType string `json:"model_type"`
	ModelID   int64  `json:"model_id"`
}

func (q *Queries) GetShareableByModelId(ctx context.Context, arg GetShareableByModelIdParams) (Shareable, error) {
	row := q.db.QueryRowContext(ctx, getShareableByModelId, arg.ModelType, arg.ModelID)
	var i Shareable
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.ModelType,
		&i.ModelID,
		&i.CreatedAt,
	)
	return i, err
}

const getShareableWithModel = `-- name: GetShareableWithModel :one
SELECT s.token, s.model_type, s.model_id, 
    b.id, b.user_id, b.location, b.title, b.wilaya, b.daira, b.building_type, b.is_promotion_building, b.is_residency, b.status, b.price, b.surface_total, b.surface_built, b.rooms, b.bathrooms, b.floors_total, b.parking_spaces, b.is_by_the_sea, b.has_water, b.has_electricity, b.has_gas, b.has_internet, b.has_garden, b.has_pool, b.has_elevator, b.has_central_heating, b.has_water_tank, b.has_air_conditioner, b.has_equipped_kitchen, b.has_terrace, b.has_notarial_deed, b.has_land_booklet, b.has_act_in_joint_ownership, b.has_certificate_of_conformity, b.has_decision, b.has_concession, b.has_stamped_paper, b.has_building_permit, b.has_off_plan_sales_contract, b.building_finished_type, b.acceptable_payment_type, b.furnished, b.year_built, b.description, b.shareable_link, b.created_at, b.updated_at, b.deleted_at,
    d.id, d.user_id, d.building_id, d.path, d.mimetype, d.size, d.thumbnail, d.created_at, d.deleted_at
FROM shareables s
LEFT JOIN buildings b ON s.model_type = 'building' AND s.model_id = b.id
LEFT JOIN building_documents d ON s.model_type = 'document' AND s.model_id = d.id
WHERE s.token = ?
`

type GetShareableWithModelRow struct {
	Token                      string          `json:"token"`
	ModelType                  string          `json:"model_type"`
	ModelID                    int64           `json:"model_id"`
	ID                         sql.NullInt64   `json:"id"`
	UserID                     sql.NullInt64   `json:"user_id"`
	Location                   sql.NullString  `json:"location"`
	Title                      sql.NullString  `json:"title"`
	Wilaya                     sql.NullString  `json:"wilaya"`
	Daira                      sql.NullString  `json:"daira"`
	BuildingType               sql.NullString  `json:"building_type"`
	IsPromotionBuilding        sql.NullBool    `json:"is_promotion_building"`
	IsResidency                sql.NullBool    `json:"is_residency"`
	Status                     sql.NullString  `json:"status"`
	Price                      sql.NullInt64   `json:"price"`
	SurfaceTotal               sql.NullFloat64 `json:"surface_total"`
	SurfaceBuilt               sql.NullFloat64 `json:"surface_built"`
	Rooms                      sql.NullInt64   `json:"rooms"`
	Bathrooms                  sql.NullInt64   `json:"bathrooms"`
	FloorsTotal                sql.NullInt64   `json:"floors_total"`
	ParkingSpaces              sql.NullInt64   `json:"parking_spaces"`
	IsByTheSea                 sql.NullBool    `json:"is_by_the_sea"`
	HasWater                   sql.NullBool    `json:"has_water"`
	HasElectricity             sql.NullBool    `json:"has_electricity"`
	HasGas                     sql.NullBool    `json:"has_gas"`
	HasInternet                sql.NullBool    `json:"has_internet"`
	HasGarden                  sql.NullBool    `json:"has_garden"`
	HasPool                    sql.NullBool    `json:"has_pool"`
	HasElevator                sql.NullBool    `json:"has_elevator"`
	HasCentralHeating          sql.NullBool    `json:"has_central_heating"`
	HasWaterTank               sql.NullBool    `json:"has_water_tank"`
	HasAirConditioner          sql.NullBool    `json:"has_air_conditioner"`
	HasEquippedKitchen         sql.NullBool    `json:"has_equipped_kitchen"`
	HasTerrace                 sql.NullBool    `json:"has_terrace"`
	HasNotarialDeed            sql.NullBool    `json:"has_notarial_deed"`
	HasLandBooklet             sql.NullBool    `json:"has_land_booklet"`
	HasActInJointOwnership     sql.NullBool    `json:"has_act_in_joint_ownership"`
	HasCertificateOfConformity sql.NullBool    `json:"has_certificate_of_conformity"`
	HasDecision                sql.NullBool    `json:"has_decision"`
	HasConcession              sql.NullBool    `json:"has_concession"`
	HasStampedPaper            sql.NullBool    `json:"has_stamped_paper"`
	HasBuildingPermit          sql.NullBool    `json:"has_building_permit"`
	HasOffPlanSalesContract    sql.NullBool    `json:"has_off_plan_sales_contract"`
	BuildingFinishedType       sql.NullString  `json:"building_finished_type"`
	AcceptablePaymentType      sql.NullString  `json:"acceptable_payment_type"`
	Furnished                  sql.NullBool    `json:"furnished"`
	YearBuilt                  sql.NullInt64   `json:"year_built"`
	Description                sql.NullString  `json:"description"`
	ShareableLink              sql.NullString  `json:"shareable_link"`
	CreatedAt                  sql.NullTime    `json:"created_at"`
	UpdatedAt                  sql.NullTime    `json:"updated_at"`
	DeletedAt                  sql.NullTime    `json:"deleted_at"`
	ID_2                       sql.NullInt64   `json:"id_2"`
	UserID_2                   sql.NullInt64   `json:"user_id_2"`
	BuildingID                 sql.NullInt64   `json:"building_id"`
	Path                       sql.NullString  `json:"path"`
	Mimetype                   sql.NullString  `json:"mimetype"`
	Size                       sql.NullInt64   `json:"size"`
	Thumbnail                  sql.NullString  `json:"thumbnail"`
	CreatedAt_2                sql.NullTime    `json:"created_at_2"`
	DeletedAt_2                sql.NullTime    `json:"deleted_at_2"`
}

func (q *Queries) GetShareableWithModel(ctx context.Context, token string) (GetShareableWithModelRow, error) {
	row := q.db.QueryRowContext(ctx, getShareableWithModel, token)
	var i GetShareableWithModelRow
	err := row.Scan(
		&i.Token,
		&i.ModelType,
		&i.ModelID,
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.Title,
		&i.Wilaya,
		&i.Daira,
		&i.BuildingType,
		&i.IsPromotionBuilding,
		&i.IsResidency,
		&i.Status,
		&i.Price,
		&i.SurfaceTotal,
		&i.SurfaceBuilt,
		&i.Rooms,
		&i.Bathrooms,
		&i.FloorsTotal,
		&i.ParkingSpaces,
		&i.IsByTheSea,
		&i.HasWater,
		&i.HasElectricity,
		&i.HasGas,
		&i.HasInternet,
		&i.HasGarden,
		&i.HasPool,
		&i.HasElevator,
		&i.HasCentralHeating,
		&i.HasWaterTank,
		&i.HasAirConditioner,
		&i.HasEquippedKitchen,
		&i.HasTerrace,
		&i.HasNotarialDeed,
		&i.HasLandBooklet,
		&i.HasActInJointOwnership,
		&i.HasCertificateOfConformity,
		&i.HasDecision,
		&i.HasConcession,
		&i.HasStampedPaper,
		&i.HasBuildingPermit,
		&i.HasOffPlanSalesContract,
		&i.BuildingFinishedType,
		&i.AcceptablePaymentType,
		&i.Furnished,
		&i.YearBuilt,
		&i.Description,
		&i.ShareableLink,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ID_2,
		&i.UserID_2,
		&i.BuildingID,
		&i.Path,
		&i.Mimetype,
		&i.Size,
		&i.Thumbnail,
		&i.CreatedAt_2,
		&i.DeletedAt_2,
	)
	return i, err
}
