// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
)

const countUsersByEmail = `-- name: CountUsersByEmail :one
SELECT COUNT(*) FROM users WHERE email = ?
`

func (q *Queries) CountUsersByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByEmailExcludingID = `-- name: CountUsersByEmailExcludingID :one
SELECT COUNT(*) FROM users
WHERE email = ? AND id != ?
`

type CountUsersByEmailExcludingIDParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) CountUsersByEmailExcludingID(ctx context.Context, arg CountUsersByEmailExcludingIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByEmailExcludingID, arg.Email, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByPhone = `-- name: CountUsersByPhone :one
SELECT COUNT(*) FROM users WHERE phone = ?
`

func (q *Queries) CountUsersByPhone(ctx context.Context, phone string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByPhone, phone)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
  fullname, role, email, phone, agency_name, agency_address,
  agency_logo, wilaya, daira, password
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	Fullname      string         `json:"fullname"`
	Role          int64          `json:"role"`
	Email         string         `json:"email"`
	Phone         string         `json:"phone"`
	AgencyName    string         `json:"agency_name"`
	AgencyAddress string         `json:"agency_address"`
	AgencyLogo    sql.NullString `json:"agency_logo"`
	Wilaya        string         `json:"wilaya"`
	Daira         string         `json:"daira"`
	Password      string         `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Fullname,
		arg.Role,
		arg.Email,
		arg.Phone,
		arg.AgencyName,
		arg.AgencyAddress,
		arg.AgencyLogo,
		arg.Wilaya,
		arg.Daira,
		arg.Password,
	)
}

const getUserAgents = `-- name: GetUserAgents :many
SELECT id, fullname, role, root_id, email, phone, agency_name, agency_address, agency_logo, wilaya, daira, password, created_at, updated_at, deleted_at from users where root_id = ?
`

func (q *Queries) GetUserAgents(ctx context.Context, rootID interface{}) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUserAgents, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Fullname,
			&i.Role,
			&i.RootID,
			&i.Email,
			&i.Phone,
			&i.AgencyName,
			&i.AgencyAddress,
			&i.AgencyLogo,
			&i.Wilaya,
			&i.Daira,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, fullname, role, root_id, email, phone, agency_name, agency_address, agency_logo, wilaya, daira, password, created_at, updated_at, deleted_at FROM users WHERE email = ? AND deleted_at is NULL LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Role,
		&i.RootID,
		&i.Email,
		&i.Phone,
		&i.AgencyName,
		&i.AgencyAddress,
		&i.AgencyLogo,
		&i.Wilaya,
		&i.Daira,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, fullname, role, root_id, email, phone, agency_name, agency_address, agency_logo, wilaya, daira, password, created_at, updated_at, deleted_at FROM users WHERE id = ? AND deleted_at is NULL LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Role,
		&i.RootID,
		&i.Email,
		&i.Phone,
		&i.AgencyName,
		&i.AgencyAddress,
		&i.AgencyLogo,
		&i.Wilaya,
		&i.Daira,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLogo = `-- name: UpdateLogo :exec
UPDATE users
SET
  agency_logo = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at is NULL
`

type UpdateLogoParams struct {
	AgencyLogo sql.NullString `json:"agency_logo"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateLogo(ctx context.Context, arg UpdateLogoParams) error {
	_, err := q.db.ExecContext(ctx, updateLogo, arg.AgencyLogo, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET
  password = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at is NULL
`

type UpdatePasswordParams struct {
	Password string `json:"password"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.Password, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
  fullname = ?,
  email = ?,
  phone = ?,
  agency_name = ?,
  agency_address = ?,
  wilaya = ?,
  daira = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at is NULL
`

type UpdateUserParams struct {
	Fullname      string `json:"fullname"`
	Email         string `json:"email"`
	Phone         string `json:"phone"`
	AgencyName    string `json:"agency_name"`
	AgencyAddress string `json:"agency_address"`
	Wilaya        string `json:"wilaya"`
	Daira         string `json:"daira"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Fullname,
		arg.Email,
		arg.Phone,
		arg.AgencyName,
		arg.AgencyAddress,
		arg.Wilaya,
		arg.Daira,
		arg.ID,
	)
	return err
}
