// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const countUsersByEmail = `-- name: CountUsersByEmail :one
SELECT COUNT(*) FROM users WHERE email = ?
`

func (q *Queries) CountUsersByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByEmailExcludingID = `-- name: CountUsersByEmailExcludingID :one
SELECT COUNT(*) FROM users
WHERE email = ? AND id != ?
`

type CountUsersByEmailExcludingIDParams struct {
	Email string `json:"email"`
	ID    int64  `json:"id"`
}

func (q *Queries) CountUsersByEmailExcludingID(ctx context.Context, arg CountUsersByEmailExcludingIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByEmailExcludingID, arg.Email, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByPhone = `-- name: CountUsersByPhone :one
SELECT COUNT(*) FROM users WHERE phone = ?
`

func (q *Queries) CountUsersByPhone(ctx context.Context, phone string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByPhone, phone)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
  fullname, role, root_id, email, phone, agency_name, agency_address,
  agency_logo, wilaya, daira, password
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateUserParams struct {
	Fullname      string         `json:"fullname"`
	Role          int64          `json:"role"`
	RootID        sql.NullInt64  `json:"root_id"`
	Email         string         `json:"email"`
	Phone         string         `json:"phone"`
	AgencyName    string         `json:"agency_name"`
	AgencyAddress string         `json:"agency_address"`
	AgencyLogo    sql.NullString `json:"agency_logo"`
	Wilaya        string         `json:"wilaya"`
	Daira         string         `json:"daira"`
	Password      string         `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Fullname,
		arg.Role,
		arg.RootID,
		arg.Email,
		arg.Phone,
		arg.AgencyName,
		arg.AgencyAddress,
		arg.AgencyLogo,
		arg.Wilaya,
		arg.Daira,
		arg.Password,
	)
}

const createUsersubscription = `-- name: CreateUsersubscription :exec
INSERT INTO user_subscriptions (
  user_id, plan_id, status, current_period_start, current_period_end, next_billing_date,
  trial_start, trial_end, amount
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateUsersubscriptionParams struct {
	UserID             int64          `json:"user_id"`
	PlanID             int64          `json:"plan_id"`
	Status             sql.NullString `json:"status"`
	CurrentPeriodStart time.Time      `json:"current_period_start"`
	CurrentPeriodEnd   time.Time      `json:"current_period_end"`
	NextBillingDate    sql.NullTime   `json:"next_billing_date"`
	TrialStart         sql.NullTime   `json:"trial_start"`
	TrialEnd           sql.NullTime   `json:"trial_end"`
	Amount             float64        `json:"amount"`
}

func (q *Queries) CreateUsersubscription(ctx context.Context, arg CreateUsersubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createUsersubscription,
		arg.UserID,
		arg.PlanID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.NextBillingDate,
		arg.TrialStart,
		arg.TrialEnd,
		arg.Amount,
	)
	return err
}

const forceDelete = `-- name: ForceDelete :exec
DELETE FROM users where id = ?
`

func (q *Queries) ForceDelete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, forceDelete, id)
	return err
}

const getAgencyUsers = `-- name: GetAgencyUsers :many
SELECT id, fullname, role, root_id, email, phone, agency_name, agency_address,
  agency_logo, wilaya, daira from users where root_id = ?
`

type GetAgencyUsersRow struct {
	ID            int64          `json:"id"`
	Fullname      string         `json:"fullname"`
	Role          int64          `json:"role"`
	RootID        sql.NullInt64  `json:"root_id"`
	Email         string         `json:"email"`
	Phone         string         `json:"phone"`
	AgencyName    string         `json:"agency_name"`
	AgencyAddress string         `json:"agency_address"`
	AgencyLogo    sql.NullString `json:"agency_logo"`
	Wilaya        string         `json:"wilaya"`
	Daira         string         `json:"daira"`
}

func (q *Queries) GetAgencyUsers(ctx context.Context, rootID sql.NullInt64) ([]GetAgencyUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAgencyUsers, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAgencyUsersRow{}
	for rows.Next() {
		var i GetAgencyUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Fullname,
			&i.Role,
			&i.RootID,
			&i.Email,
			&i.Phone,
			&i.AgencyName,
			&i.AgencyAddress,
			&i.AgencyLogo,
			&i.Wilaya,
			&i.Daira,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrentUserSubscription = `-- name: GetCurrentUserSubscription :one
SELECT id, user_id, plan_id, status, current_period_start, current_period_end, next_billing_date, trial_start, trial_end, amount, created_at, updated_at FROM user_subscriptions where user_id = ? ORDER by id desc limit 1
`

func (q *Queries) GetCurrentUserSubscription(ctx context.Context, userID int64) (UserSubscription, error) {
	row := q.db.QueryRowContext(ctx, getCurrentUserSubscription, userID)
	var i UserSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextBillingDate,
		&i.TrialStart,
		&i.TrialEnd,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, fullname, role, root_id, email, phone, agency_name, agency_address, agency_logo, wilaya, daira, password, created_at, updated_at, deleted_at FROM users where id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Role,
		&i.RootID,
		&i.Email,
		&i.Phone,
		&i.AgencyName,
		&i.AgencyAddress,
		&i.AgencyLogo,
		&i.Wilaya,
		&i.Daira,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserAgents = `-- name: GetUserAgents :many
SELECT id, fullname, role, root_id, email, phone, agency_name, agency_address,
  agency_logo, wilaya, daira from users where root_id = ?
`

type GetUserAgentsRow struct {
	ID            int64          `json:"id"`
	Fullname      string         `json:"fullname"`
	Role          int64          `json:"role"`
	RootID        sql.NullInt64  `json:"root_id"`
	Email         string         `json:"email"`
	Phone         string         `json:"phone"`
	AgencyName    string         `json:"agency_name"`
	AgencyAddress string         `json:"agency_address"`
	AgencyLogo    sql.NullString `json:"agency_logo"`
	Wilaya        string         `json:"wilaya"`
	Daira         string         `json:"daira"`
}

func (q *Queries) GetUserAgents(ctx context.Context, rootID sql.NullInt64) ([]GetUserAgentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserAgents, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserAgentsRow{}
	for rows.Next() {
		var i GetUserAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Fullname,
			&i.Role,
			&i.RootID,
			&i.Email,
			&i.Phone,
			&i.AgencyName,
			&i.AgencyAddress,
			&i.AgencyLogo,
			&i.Wilaya,
			&i.Daira,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, fullname, role, root_id, email, phone, agency_name, agency_address, agency_logo, wilaya, daira, password, created_at, updated_at, deleted_at FROM users WHERE email = ? AND deleted_at is NULL LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Role,
		&i.RootID,
		&i.Email,
		&i.Phone,
		&i.AgencyName,
		&i.AgencyAddress,
		&i.AgencyLogo,
		&i.Wilaya,
		&i.Daira,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, fullname, role, root_id, email, phone, agency_name, agency_address,
  agency_logo, wilaya, daira FROM users WHERE id = ? AND deleted_at is NULL LIMIT 1
`

type GetUserByIdRow struct {
	ID            int64          `json:"id"`
	Fullname      string         `json:"fullname"`
	Role          int64          `json:"role"`
	RootID        sql.NullInt64  `json:"root_id"`
	Email         string         `json:"email"`
	Phone         string         `json:"phone"`
	AgencyName    string         `json:"agency_name"`
	AgencyAddress string         `json:"agency_address"`
	AgencyLogo    sql.NullString `json:"agency_logo"`
	Wilaya        string         `json:"wilaya"`
	Daira         string         `json:"daira"`
}

func (q *Queries) GetUserById(ctx context.Context, id int64) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i GetUserByIdRow
	err := row.Scan(
		&i.ID,
		&i.Fullname,
		&i.Role,
		&i.RootID,
		&i.Email,
		&i.Phone,
		&i.AgencyName,
		&i.AgencyAddress,
		&i.AgencyLogo,
		&i.Wilaya,
		&i.Daira,
	)
	return i, err
}

const getUserSubscriptions = `-- name: GetUserSubscriptions :many
SELECT id, user_id, plan_id, status, current_period_start, current_period_end, next_billing_date, trial_start, trial_end, amount, created_at, updated_at from user_subscriptions where user_id = ? ORDER BY id DESC
`

func (q *Queries) GetUserSubscriptions(ctx context.Context, userID int64) ([]UserSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSubscription{}
	for rows.Next() {
		var i UserSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextBillingDate,
			&i.TrialStart,
			&i.TrialEnd,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgencyUsersSubscriptionStatus = `-- name: UpdateAgencyUsersSubscriptionStatus :exec
UPDATE user_subscriptions SET status = ? WHERE user_id IN(/*SLICE:users_id*/?)
`

type UpdateAgencyUsersSubscriptionStatusParams struct {
	Status  sql.NullString `json:"status"`
	UsersID []int64        `json:"users_id"`
}

func (q *Queries) UpdateAgencyUsersSubscriptionStatus(ctx context.Context, arg UpdateAgencyUsersSubscriptionStatusParams) error {
	query := updateAgencyUsersSubscriptionStatus
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Status)
	if len(arg.UsersID) > 0 {
		for _, v := range arg.UsersID {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:users_id*/?", strings.Repeat(",?", len(arg.UsersID))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:users_id*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const updateLogo = `-- name: UpdateLogo :exec
UPDATE users
SET
  agency_logo = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at is NULL
`

type UpdateLogoParams struct {
	AgencyLogo sql.NullString `json:"agency_logo"`
	ID         int64          `json:"id"`
}

func (q *Queries) UpdateLogo(ctx context.Context, arg UpdateLogoParams) error {
	_, err := q.db.ExecContext(ctx, updateLogo, arg.AgencyLogo, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET
  password = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at is NULL
`

type UpdatePasswordParams struct {
	Password string `json:"password"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.Password, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
  fullname = ?,
  email = ?,
  phone = ?,
  agency_name = ?,
  agency_address = ?,
  wilaya = ?,
  daira = ?,
  updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND deleted_at is NULL
`

type UpdateUserParams struct {
	Fullname      string `json:"fullname"`
	Email         string `json:"email"`
	Phone         string `json:"phone"`
	AgencyName    string `json:"agency_name"`
	AgencyAddress string `json:"agency_address"`
	Wilaya        string `json:"wilaya"`
	Daira         string `json:"daira"`
	ID            int64  `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Fullname,
		arg.Email,
		arg.Phone,
		arg.AgencyName,
		arg.AgencyAddress,
		arg.Wilaya,
		arg.Daira,
		arg.ID,
	)
	return err
}

const updateUserSubscription = `-- name: UpdateUserSubscription :exec
UPDATE user_subscriptions 
SET 
    plan_id = ?,
    status = ?,
    current_period_start = ?,
    current_period_end = ?,
    next_billing_date = ?,
    trial_start = ?,
    trial_end = ?,
    amount = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateUserSubscriptionParams struct {
	PlanID             int64          `json:"plan_id"`
	Status             sql.NullString `json:"status"`
	CurrentPeriodStart time.Time      `json:"current_period_start"`
	CurrentPeriodEnd   time.Time      `json:"current_period_end"`
	NextBillingDate    sql.NullTime   `json:"next_billing_date"`
	TrialStart         sql.NullTime   `json:"trial_start"`
	TrialEnd           sql.NullTime   `json:"trial_end"`
	Amount             float64        `json:"amount"`
	ID                 int64          `json:"id"`
}

func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, updateUserSubscription,
		arg.PlanID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.NextBillingDate,
		arg.TrialStart,
		arg.TrialEnd,
		arg.Amount,
		arg.ID,
	)
	return err
}
