// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: building.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createBuilding = `-- name: CreateBuilding :execresult
INSERT INTO buildings (
  user_id, location, title, wilaya, daira, building_type, is_promotion_building, is_residency,
  status, price, surface_total, surface_built, rooms, bathrooms, floors_total, parking_spaces,
  is_by_the_sea, has_water, has_electricity, has_gas, has_internet, has_garden, has_pool,
  has_elevator, has_central_heating, has_water_tank, has_air_conditioner, has_equipped_kitchen,
  has_terrace, has_notarial_deed, has_land_booklet, has_act_in_joint_ownership,
  has_certificate_of_conformity, has_decision, has_concession, has_stamped_paper,
  has_building_permit, has_off_plan_sales_contract, building_finished_type,
  acceptable_payment_type, furnished, year_built, description, shareable_link
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreateBuildingParams struct {
	UserID                     int64           `json:"user_id"`
	Location                   sql.NullString  `json:"location"`
	Title                      sql.NullString  `json:"title"`
	Wilaya                     sql.NullString  `json:"wilaya"`
	Daira                      sql.NullString  `json:"daira"`
	BuildingType               sql.NullString  `json:"building_type"`
	IsPromotionBuilding        sql.NullBool    `json:"is_promotion_building"`
	IsResidency                sql.NullBool    `json:"is_residency"`
	Status                     sql.NullString  `json:"status"`
	Price                      sql.NullInt64   `json:"price"`
	SurfaceTotal               sql.NullFloat64 `json:"surface_total"`
	SurfaceBuilt               sql.NullFloat64 `json:"surface_built"`
	Rooms                      sql.NullInt64   `json:"rooms"`
	Bathrooms                  sql.NullInt64   `json:"bathrooms"`
	FloorsTotal                sql.NullInt64   `json:"floors_total"`
	ParkingSpaces              sql.NullInt64   `json:"parking_spaces"`
	IsByTheSea                 sql.NullBool    `json:"is_by_the_sea"`
	HasWater                   sql.NullBool    `json:"has_water"`
	HasElectricity             sql.NullBool    `json:"has_electricity"`
	HasGas                     sql.NullBool    `json:"has_gas"`
	HasInternet                sql.NullBool    `json:"has_internet"`
	HasGarden                  sql.NullBool    `json:"has_garden"`
	HasPool                    sql.NullBool    `json:"has_pool"`
	HasElevator                sql.NullBool    `json:"has_elevator"`
	HasCentralHeating          sql.NullBool    `json:"has_central_heating"`
	HasWaterTank               sql.NullBool    `json:"has_water_tank"`
	HasAirConditioner          sql.NullBool    `json:"has_air_conditioner"`
	HasEquippedKitchen         sql.NullBool    `json:"has_equipped_kitchen"`
	HasTerrace                 sql.NullBool    `json:"has_terrace"`
	HasNotarialDeed            sql.NullBool    `json:"has_notarial_deed"`
	HasLandBooklet             sql.NullBool    `json:"has_land_booklet"`
	HasActInJointOwnership     sql.NullBool    `json:"has_act_in_joint_ownership"`
	HasCertificateOfConformity sql.NullBool    `json:"has_certificate_of_conformity"`
	HasDecision                sql.NullBool    `json:"has_decision"`
	HasConcession              sql.NullBool    `json:"has_concession"`
	HasStampedPaper            sql.NullBool    `json:"has_stamped_paper"`
	HasBuildingPermit          sql.NullBool    `json:"has_building_permit"`
	HasOffPlanSalesContract    sql.NullBool    `json:"has_off_plan_sales_contract"`
	BuildingFinishedType       sql.NullString  `json:"building_finished_type"`
	AcceptablePaymentType      sql.NullString  `json:"acceptable_payment_type"`
	Furnished                  sql.NullBool    `json:"furnished"`
	YearBuilt                  interface{}     `json:"year_built"`
	Description                sql.NullString  `json:"description"`
	ShareableLink              sql.NullString  `json:"shareable_link"`
}

func (q *Queries) CreateBuilding(ctx context.Context, arg CreateBuildingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createBuilding,
		arg.UserID,
		arg.Location,
		arg.Title,
		arg.Wilaya,
		arg.Daira,
		arg.BuildingType,
		arg.IsPromotionBuilding,
		arg.IsResidency,
		arg.Status,
		arg.Price,
		arg.SurfaceTotal,
		arg.SurfaceBuilt,
		arg.Rooms,
		arg.Bathrooms,
		arg.FloorsTotal,
		arg.ParkingSpaces,
		arg.IsByTheSea,
		arg.HasWater,
		arg.HasElectricity,
		arg.HasGas,
		arg.HasInternet,
		arg.HasGarden,
		arg.HasPool,
		arg.HasElevator,
		arg.HasCentralHeating,
		arg.HasWaterTank,
		arg.HasAirConditioner,
		arg.HasEquippedKitchen,
		arg.HasTerrace,
		arg.HasNotarialDeed,
		arg.HasLandBooklet,
		arg.HasActInJointOwnership,
		arg.HasCertificateOfConformity,
		arg.HasDecision,
		arg.HasConcession,
		arg.HasStampedPaper,
		arg.HasBuildingPermit,
		arg.HasOffPlanSalesContract,
		arg.BuildingFinishedType,
		arg.AcceptablePaymentType,
		arg.Furnished,
		arg.YearBuilt,
		arg.Description,
		arg.ShareableLink,
	)
}

const createBuildingDocument = `-- name: CreateBuildingDocument :exec
INSERT INTO building_documents (user_id, building_id, path, mimetype, size, thumbnail)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateBuildingDocumentParams struct {
	UserID     int64          `json:"user_id"`
	BuildingID int64          `json:"building_id"`
	Path       string         `json:"path"`
	Mimetype   sql.NullString `json:"mimetype"`
	Size       sql.NullInt64  `json:"size"`
	Thumbnail  sql.NullString `json:"thumbnail"`
}

func (q *Queries) CreateBuildingDocument(ctx context.Context, arg CreateBuildingDocumentParams) error {
	_, err := q.db.ExecContext(ctx, createBuildingDocument,
		arg.UserID,
		arg.BuildingID,
		arg.Path,
		arg.Mimetype,
		arg.Size,
		arg.Thumbnail,
	)
	return err
}

const createBuildingImage = `-- name: CreateBuildingImage :exec
INSERT INTO building_images (user_id, building_id, path, mimetype, size)
VALUES (?, ?, ?, ?, ?)
`

type CreateBuildingImageParams struct {
	UserID     int64          `json:"user_id"`
	BuildingID int64          `json:"building_id"`
	Path       string         `json:"path"`
	Mimetype   sql.NullString `json:"mimetype"`
	Size       sql.NullInt64  `json:"size"`
}

func (q *Queries) CreateBuildingImage(ctx context.Context, arg CreateBuildingImageParams) error {
	_, err := q.db.ExecContext(ctx, createBuildingImage,
		arg.UserID,
		arg.BuildingID,
		arg.Path,
		arg.Mimetype,
		arg.Size,
	)
	return err
}

const getBuilding = `-- name: GetBuilding :one
SELECT id, user_id, location, title, wilaya, daira, building_type, is_promotion_building, is_residency, status, price, surface_total, surface_built, rooms, bathrooms, floors_total, parking_spaces, is_by_the_sea, has_water, has_electricity, has_gas, has_internet, has_garden, has_pool, has_elevator, has_central_heating, has_water_tank, has_air_conditioner, has_equipped_kitchen, has_terrace, has_notarial_deed, has_land_booklet, has_act_in_joint_ownership, has_certificate_of_conformity, has_decision, has_concession, has_stamped_paper, has_building_permit, has_off_plan_sales_contract, building_finished_type, acceptable_payment_type, furnished, year_built, description, shareable_link, created_at, updated_at FROM buildings
WHERE user_id = ? AND id = ?
`

type GetBuildingParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) GetBuilding(ctx context.Context, arg GetBuildingParams) (Building, error) {
	row := q.db.QueryRowContext(ctx, getBuilding, arg.UserID, arg.ID)
	var i Building
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Location,
		&i.Title,
		&i.Wilaya,
		&i.Daira,
		&i.BuildingType,
		&i.IsPromotionBuilding,
		&i.IsResidency,
		&i.Status,
		&i.Price,
		&i.SurfaceTotal,
		&i.SurfaceBuilt,
		&i.Rooms,
		&i.Bathrooms,
		&i.FloorsTotal,
		&i.ParkingSpaces,
		&i.IsByTheSea,
		&i.HasWater,
		&i.HasElectricity,
		&i.HasGas,
		&i.HasInternet,
		&i.HasGarden,
		&i.HasPool,
		&i.HasElevator,
		&i.HasCentralHeating,
		&i.HasWaterTank,
		&i.HasAirConditioner,
		&i.HasEquippedKitchen,
		&i.HasTerrace,
		&i.HasNotarialDeed,
		&i.HasLandBooklet,
		&i.HasActInJointOwnership,
		&i.HasCertificateOfConformity,
		&i.HasDecision,
		&i.HasConcession,
		&i.HasStampedPaper,
		&i.HasBuildingPermit,
		&i.HasOffPlanSalesContract,
		&i.BuildingFinishedType,
		&i.AcceptablePaymentType,
		&i.Furnished,
		&i.YearBuilt,
		&i.Description,
		&i.ShareableLink,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentsForBuildingIDs = `-- name: ListDocumentsForBuildingIDs :many
SELECT id, user_id, building_id, path, mimetype, size, thumbnail, created_at FROM building_documents
WHERE building_id IN (/*SLICE:building_ids*/?)
`

func (q *Queries) ListDocumentsForBuildingIDs(ctx context.Context, buildingIds []int64) ([]BuildingDocument, error) {
	query := listDocumentsForBuildingIDs
	var queryParams []interface{}
	if len(buildingIds) > 0 {
		for _, v := range buildingIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:building_ids*/?", strings.Repeat(",?", len(buildingIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:building_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildingDocument{}
	for rows.Next() {
		var i BuildingDocument
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BuildingID,
			&i.Path,
			&i.Mimetype,
			&i.Size,
			&i.Thumbnail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesForBuildingIDs = `-- name: ListImagesForBuildingIDs :many
SELECT id, user_id, building_id, path, mimetype, size, created_at FROM building_images
WHERE building_id IN (/*SLICE:building_ids*/?)
`

func (q *Queries) ListImagesForBuildingIDs(ctx context.Context, buildingIds []int64) ([]BuildingImage, error) {
	query := listImagesForBuildingIDs
	var queryParams []interface{}
	if len(buildingIds) > 0 {
		for _, v := range buildingIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:building_ids*/?", strings.Repeat(",?", len(buildingIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:building_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BuildingImage{}
	for rows.Next() {
		var i BuildingImage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BuildingID,
			&i.Path,
			&i.Mimetype,
			&i.Size,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaginatedBuildings = `-- name: ListPaginatedBuildings :many
SELECT id, user_id, location, title, wilaya, daira, building_type, is_promotion_building, is_residency, status, price, surface_total, surface_built, rooms, bathrooms, floors_total, parking_spaces, is_by_the_sea, has_water, has_electricity, has_gas, has_internet, has_garden, has_pool, has_elevator, has_central_heating, has_water_tank, has_air_conditioner, has_equipped_kitchen, has_terrace, has_notarial_deed, has_land_booklet, has_act_in_joint_ownership, has_certificate_of_conformity, has_decision, has_concession, has_stamped_paper, has_building_permit, has_off_plan_sales_contract, building_finished_type, acceptable_payment_type, furnished, year_built, description, shareable_link, created_at, updated_at FROM buildings
WHERE user_id = ?
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type ListPaginatedBuildingsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListPaginatedBuildings(ctx context.Context, arg ListPaginatedBuildingsParams) ([]Building, error) {
	rows, err := q.db.QueryContext(ctx, listPaginatedBuildings, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Building{}
	for rows.Next() {
		var i Building
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Location,
			&i.Title,
			&i.Wilaya,
			&i.Daira,
			&i.BuildingType,
			&i.IsPromotionBuilding,
			&i.IsResidency,
			&i.Status,
			&i.Price,
			&i.SurfaceTotal,
			&i.SurfaceBuilt,
			&i.Rooms,
			&i.Bathrooms,
			&i.FloorsTotal,
			&i.ParkingSpaces,
			&i.IsByTheSea,
			&i.HasWater,
			&i.HasElectricity,
			&i.HasGas,
			&i.HasInternet,
			&i.HasGarden,
			&i.HasPool,
			&i.HasElevator,
			&i.HasCentralHeating,
			&i.HasWaterTank,
			&i.HasAirConditioner,
			&i.HasEquippedKitchen,
			&i.HasTerrace,
			&i.HasNotarialDeed,
			&i.HasLandBooklet,
			&i.HasActInJointOwnership,
			&i.HasCertificateOfConformity,
			&i.HasDecision,
			&i.HasConcession,
			&i.HasStampedPaper,
			&i.HasBuildingPermit,
			&i.HasOffPlanSalesContract,
			&i.BuildingFinishedType,
			&i.AcceptablePaymentType,
			&i.Furnished,
			&i.YearBuilt,
			&i.Description,
			&i.ShareableLink,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
