// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: calendar.sql

package db

import (
	"context"
	"time"
)

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendar_events (
    user_id, title, content, for_date
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, user_id, title, content, for_date, created_at, updated_at, deleted_at
`

type CreateCalendarParams struct {
	UserID  int64     `json:"user_id"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
	ForDate time.Time `json:"for_date"`
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, createCalendar,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.ForDate,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.ForDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCalendar = `-- name: DeleteCalendar :exec
UPDATE calendar_events set deleted_at = CURRENT_TIMESTAMP where id = ? and user_id = ?
`

type DeleteCalendarParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteCalendar(ctx context.Context, arg DeleteCalendarParams) error {
	_, err := q.db.ExecContext(ctx, deleteCalendar, arg.ID, arg.UserID)
	return err
}

const getUserCalendars = `-- name: GetUserCalendars :many
SELECT id, user_id, title, content, for_date, created_at, updated_at, deleted_at from calendar_events where user_id = ? and deleted_at is null
`

func (q *Queries) GetUserCalendars(ctx context.Context, userID int64) ([]CalendarEvent, error) {
	rows, err := q.db.QueryContext(ctx, getUserCalendars, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarEvent{}
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Content,
			&i.ForDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendar = `-- name: UpdateCalendar :exec
UPDATE calendar_events SET
title = ?,
content = ?,
for_date = ?,
updated_at = CURRENT_TIMESTAMP
WHERE id = ? and user_id = ?
`

type UpdateCalendarParams struct {
	Title   string    `json:"title"`
	Content string    `json:"content"`
	ForDate time.Time `json:"for_date"`
	ID      int64     `json:"id"`
	UserID  int64     `json:"user_id"`
}

func (q *Queries) UpdateCalendar(ctx context.Context, arg UpdateCalendarParams) error {
	_, err := q.db.ExecContext(ctx, updateCalendar,
		arg.Title,
		arg.Content,
		arg.ForDate,
		arg.ID,
		arg.UserID,
	)
	return err
}
