// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: contact.sql

package db

import (
	"context"
	"database/sql"
)

const countContactsByEmail = `-- name: CountContactsByEmail :one
SELECT COUNT(*) FROM contacts WHERE email = ?
`

func (q *Queries) CountContactsByEmail(ctx context.Context, email sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContactsByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContactsByPhone = `-- name: CountContactsByPhone :one
SELECT COUNT(*) FROM contacts WHERE phone = ?
`

func (q *Queries) CountContactsByPhone(ctx context.Context, phone sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContactsByPhone, phone)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContact = `-- name: CreateContact :execresult
INSERT INTO contacts (
  user_id,
  fullname,
  phone,
  email,
  wilaya,
  daira,
  client_type,
  searching_for,
  preferred_location_type,
  house_finishing,
  renting_floor_looking_for,
  is_married,
  min_budget,
  max_budget,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
`

type CreateContactParams struct {
	UserID                 int64          `json:"user_id"`
	Fullname               string         `json:"fullname"`
	Phone                  sql.NullString `json:"phone"`
	Email                  sql.NullString `json:"email"`
	Wilaya                 sql.NullString `json:"wilaya"`
	Daira                  sql.NullString `json:"daira"`
	ClientType             sql.NullString `json:"client_type"`
	SearchingFor           sql.NullString `json:"searching_for"`
	PreferredLocationType  sql.NullString `json:"preferred_location_type"`
	HouseFinishing         sql.NullString `json:"house_finishing"`
	RentingFloorLookingFor sql.NullString `json:"renting_floor_looking_for"`
	IsMarried              sql.NullBool   `json:"is_married"`
	MinBudget              sql.NullInt64  `json:"min_budget"`
	MaxBudget              sql.NullInt64  `json:"max_budget"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createContact,
		arg.UserID,
		arg.Fullname,
		arg.Phone,
		arg.Email,
		arg.Wilaya,
		arg.Daira,
		arg.ClientType,
		arg.SearchingFor,
		arg.PreferredLocationType,
		arg.HouseFinishing,
		arg.RentingFloorLookingFor,
		arg.IsMarried,
		arg.MinBudget,
		arg.MaxBudget,
	)
}
