// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: contact.sql

package db

import (
	"context"
	"database/sql"
)

const countContactsByEmail = `-- name: CountContactsByEmail :one
SELECT COUNT(*) FROM contacts WHERE email = ?
`

func (q *Queries) CountContactsByEmail(ctx context.Context, email sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContactsByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countContactsByPhone = `-- name: CountContactsByPhone :one
SELECT COUNT(*) FROM contacts WHERE phone = ?
`

func (q *Queries) CountContactsByPhone(ctx context.Context, phone sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countContactsByPhone, phone)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContact = `-- name: CreateContact :execresult
INSERT INTO contacts (
  user_id,
  fullname,
  phone,
  email,
  wilaya,
  daira,
  client_type,
  searching_for,
  preferred_location_type,
  house_finishing,
  renting_floor_looking_for,
  is_married,
  min_budget,
  max_budget,
  created_at,
  updated_at
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
)
`

type CreateContactParams struct {
	UserID                 int64          `json:"user_id"`
	Fullname               string         `json:"fullname"`
	Phone                  sql.NullString `json:"phone"`
	Email                  sql.NullString `json:"email"`
	Wilaya                 sql.NullString `json:"wilaya"`
	Daira                  sql.NullString `json:"daira"`
	ClientType             sql.NullString `json:"client_type"`
	SearchingFor           sql.NullString `json:"searching_for"`
	PreferredLocationType  sql.NullString `json:"preferred_location_type"`
	HouseFinishing         sql.NullString `json:"house_finishing"`
	RentingFloorLookingFor sql.NullString `json:"renting_floor_looking_for"`
	IsMarried              sql.NullBool   `json:"is_married"`
	MinBudget              sql.NullInt64  `json:"min_budget"`
	MaxBudget              sql.NullInt64  `json:"max_budget"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createContact,
		arg.UserID,
		arg.Fullname,
		arg.Phone,
		arg.Email,
		arg.Wilaya,
		arg.Daira,
		arg.ClientType,
		arg.SearchingFor,
		arg.PreferredLocationType,
		arg.HouseFinishing,
		arg.RentingFloorLookingFor,
		arg.IsMarried,
		arg.MinBudget,
		arg.MaxBudget,
	)
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts
WHERE id = ? AND user_id = ?
`

type DeleteContactParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteContact(ctx context.Context, arg DeleteContactParams) error {
	_, err := q.db.ExecContext(ctx, deleteContact, arg.ID, arg.UserID)
	return err
}

const getAllContacts = `-- name: GetAllContacts :many
SELECT
  id,
  user_id,
  fullname,
  phone,
  email,
  wilaya,
  daira,
  client_type,
  searching_for,
  preferred_location_type,
  house_finishing,
  renting_floor_looking_for,
  is_married,
  min_budget,
  max_budget,
  created_at,
  updated_at
FROM contacts
WHERE user_id = ?
ORDER BY id DESC
`

func (q *Queries) GetAllContacts(ctx context.Context, userID int64) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, getAllContacts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Fullname,
			&i.Phone,
			&i.Email,
			&i.Wilaya,
			&i.Daira,
			&i.ClientType,
			&i.SearchingFor,
			&i.PreferredLocationType,
			&i.HouseFinishing,
			&i.RentingFloorLookingFor,
			&i.IsMarried,
			&i.MinBudget,
			&i.MaxBudget,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContact = `-- name: GetContact :one
SELECT
  id,
  user_id,
  fullname,
  phone,
  email,
  wilaya,
  daira,
  client_type,
  searching_for,
  preferred_location_type,
  house_finishing,
  renting_floor_looking_for,
  is_married,
  min_budget,
  max_budget,
  created_at,
  updated_at
FROM contacts
WHERE id = ? AND user_id = ?
`

type GetContactParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContact, arg.ID, arg.UserID)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Fullname,
		&i.Phone,
		&i.Email,
		&i.Wilaya,
		&i.Daira,
		&i.ClientType,
		&i.SearchingFor,
		&i.PreferredLocationType,
		&i.HouseFinishing,
		&i.RentingFloorLookingFor,
		&i.IsMarried,
		&i.MinBudget,
		&i.MaxBudget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
