// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type User struct {
	ID            int64          `json:"id"`
	Fullname      string         `json:"fullname"`
	Role          int64          `json:"role"`
	Email         string         `json:"email"`
	Phone         string         `json:"phone"`
	AgencyName    string         `json:"agency_name"`
	AgencyAddress string         `json:"agency_address"`
	AgencyLogo    sql.NullString `json:"agency_logo"`
	Wilaya        string         `json:"wilaya"`
	Daira         string         `json:"daira"`
	Password      interface{}    `json:"password"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}
