// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Contact struct {
	ID                     int64          `json:"id"`
	UserID                 int64          `json:"user_id"`
	Fullname               string         `json:"fullname"`
	Phone                  sql.NullString `json:"phone"`
	Email                  sql.NullString `json:"email"`
	Wilaya                 sql.NullString `json:"wilaya"`
	Daira                  sql.NullString `json:"daira"`
	ClientType             sql.NullString `json:"client_type"`
	SearchingFor           sql.NullString `json:"searching_for"`
	PreferredLocationType  sql.NullString `json:"preferred_location_type"`
	HouseFinishing         sql.NullString `json:"house_finishing"`
	RentingFloorLookingFor sql.NullString `json:"renting_floor_looking_for"`
	IsMarried              sql.NullBool   `json:"is_married"`
	MinBudget              sql.NullInt64  `json:"min_budget"`
	MaxBudget              sql.NullInt64  `json:"max_budget"`
	CreatedAt              sql.NullTime   `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
}

type User struct {
	ID            int64          `json:"id"`
	Fullname      string         `json:"fullname"`
	Role          int64          `json:"role"`
	Email         string         `json:"email"`
	Phone         string         `json:"phone"`
	AgencyName    string         `json:"agency_name"`
	AgencyAddress string         `json:"agency_address"`
	AgencyLogo    sql.NullString `json:"agency_logo"`
	Wilaya        string         `json:"wilaya"`
	Daira         string         `json:"daira"`
	Password      string         `json:"password"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
}
