// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sms_queue.sql

package db

import (
	"context"
	"database/sql"
)

const addSMSQueueContact = `-- name: AddSMSQueueContact :one
INSERT INTO sms_queue_contacts (
    sms_queue_id, phone_number
) VALUES (
    ?, ?
)
RETURNING id, sms_queue_id, phone_number, status, error, sent_at
`

type AddSMSQueueContactParams struct {
	SmsQueueID  int64  `json:"sms_queue_id"`
	PhoneNumber string `json:"phone_number"`
}

func (q *Queries) AddSMSQueueContact(ctx context.Context, arg AddSMSQueueContactParams) (SmsQueueContact, error) {
	row := q.db.QueryRowContext(ctx, addSMSQueueContact, arg.SmsQueueID, arg.PhoneNumber)
	var i SmsQueueContact
	err := row.Scan(
		&i.ID,
		&i.SmsQueueID,
		&i.PhoneNumber,
		&i.Status,
		&i.Error,
		&i.SentAt,
	)
	return i, err
}

const createSMSQueue = `-- name: CreateSMSQueue :one
INSERT INTO sms_queues (
    user_id, title, content, from_number, total_recipients, scheduled_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, user_id, title, content, from_number, status, total_recipients, sent_count, failed_count, created_at, scheduled_at, sent_at
`

type CreateSMSQueueParams struct {
	UserID          int64        `json:"user_id"`
	Title           string       `json:"title"`
	Content         string       `json:"content"`
	FromNumber      string       `json:"from_number"`
	TotalRecipients int64        `json:"total_recipients"`
	ScheduledAt     sql.NullTime `json:"scheduled_at"`
}

func (q *Queries) CreateSMSQueue(ctx context.Context, arg CreateSMSQueueParams) (SmsQueue, error) {
	row := q.db.QueryRowContext(ctx, createSMSQueue,
		arg.UserID,
		arg.Title,
		arg.Content,
		arg.FromNumber,
		arg.TotalRecipients,
		arg.ScheduledAt,
	)
	var i SmsQueue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.FromNumber,
		&i.Status,
		&i.TotalRecipients,
		&i.SentCount,
		&i.FailedCount,
		&i.CreatedAt,
		&i.ScheduledAt,
		&i.SentAt,
	)
	return i, err
}

const getSmsContacts = `-- name: GetSmsContacts :many
SELECT id, sms_queue_id, phone_number, status, error, sent_at from sms_queue_contacts where sms_queue_id = ?
`

func (q *Queries) GetSmsContacts(ctx context.Context, smsQueueID int64) ([]SmsQueueContact, error) {
	rows, err := q.db.QueryContext(ctx, getSmsContacts, smsQueueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SmsQueueContact{}
	for rows.Next() {
		var i SmsQueueContact
		if err := rows.Scan(
			&i.ID,
			&i.SmsQueueID,
			&i.PhoneNumber,
			&i.Status,
			&i.Error,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSmsQueue = `-- name: GetSmsQueue :one
SELECT id, user_id, title, content, from_number, status, total_recipients, sent_count, failed_count, created_at, scheduled_at, sent_at from sms_queues where id = ? LIMIT 1
`

func (q *Queries) GetSmsQueue(ctx context.Context, id int64) (SmsQueue, error) {
	row := q.db.QueryRowContext(ctx, getSmsQueue, id)
	var i SmsQueue
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Content,
		&i.FromNumber,
		&i.Status,
		&i.TotalRecipients,
		&i.SentCount,
		&i.FailedCount,
		&i.CreatedAt,
		&i.ScheduledAt,
		&i.SentAt,
	)
	return i, err
}
