// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: task.sql

package db

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    to_id, title, content, due_date, root_id
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, to_id, title, content, is_completed, due_date, created_at, updated_at, deleted_at, root_id
`

type CreateTaskParams struct {
	ToID    int64         `json:"to_id"`
	Title   string        `json:"title"`
	Content interface{}   `json:"content"`
	DueDate sql.NullTime  `json:"due_date"`
	RootID  sql.NullInt64 `json:"root_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ToID,
		arg.Title,
		arg.Content,
		arg.DueDate,
		arg.RootID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ToID,
		&i.Title,
		&i.Content,
		&i.IsCompleted,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RootID,
	)
	return i, err
}

const getCurrentUserTasks = `-- name: GetCurrentUserTasks :many
SELECT id, to_id, title, content, is_completed, due_date, created_at, updated_at, deleted_at, root_id from tasks where to_id = ?
`

func (q *Queries) GetCurrentUserTasks(ctx context.Context, toID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getCurrentUserTasks, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ToID,
			&i.Title,
			&i.Content,
			&i.IsCompleted,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RootID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRootUserCreatedTasks = `-- name: GetRootUserCreatedTasks :many
SELECT id, to_id, title, content, is_completed, due_date, created_at, updated_at, deleted_at, root_id from tasks where root_id = ? OR to_id = ?
`

type GetRootUserCreatedTasksParams struct {
	RootID sql.NullInt64 `json:"root_id"`
	ToID   int64         `json:"to_id"`
}

func (q *Queries) GetRootUserCreatedTasks(ctx context.Context, arg GetRootUserCreatedTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getRootUserCreatedTasks, arg.RootID, arg.ToID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ToID,
			&i.Title,
			&i.Content,
			&i.IsCompleted,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RootID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskAsDone = `-- name: MarkTaskAsDone :exec
UPDATE tasks
SET 
is_completed = 1,
updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND (to_id = ? OR root_id = ?)
`

type MarkTaskAsDoneParams struct {
	ID     int64         `json:"id"`
	ToID   int64         `json:"to_id"`
	RootID sql.NullInt64 `json:"root_id"`
}

func (q *Queries) MarkTaskAsDone(ctx context.Context, arg MarkTaskAsDoneParams) error {
	_, err := q.db.ExecContext(ctx, markTaskAsDone, arg.ID, arg.ToID, arg.RootID)
	return err
}
